# Generated by Django 5.1.1 on 2024-10-13 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jenjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'jenjang',
            },
        ),
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIK', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('guru profesional', 'Guru Profesional'), ('guru bulanan', 'Guru Bulanan'), ('guru ekstrakurikuler', 'Guru Ekstrakurikuler'), ('korlap', 'Korlap'), ('teknisi', 'Teknisi')], max_length=255)),
                ('sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Karyawan',
            },
        ),
        migrations.CreateModel(
            name='kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='omset_buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(max_length=255)),
                ('januari', models.IntegerField()),
                ('februari', models.IntegerField()),
                ('maret', models.IntegerField()),
                ('april', models.IntegerField()),
                ('mei', models.IntegerField()),
                ('juni', models.IntegerField()),
                ('juli', models.IntegerField()),
                ('agustus', models.IntegerField()),
                ('september', models.IntegerField()),
                ('oktober', models.IntegerField()),
                ('november', models.IntegerField()),
                ('desember', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Omset Buku',
            },
        ),
        migrations.CreateModel(
            name='omset_hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(max_length=255)),
                ('januari', models.IntegerField()),
                ('februari', models.IntegerField()),
                ('maret', models.IntegerField()),
                ('april', models.IntegerField()),
                ('mei', models.IntegerField()),
                ('juni', models.IntegerField()),
                ('juli', models.IntegerField()),
                ('agustus', models.IntegerField()),
                ('september', models.IntegerField()),
                ('oktober', models.IntegerField()),
                ('november', models.IntegerField()),
                ('desember', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Omset Hardware',
            },
        ),
        migrations.CreateModel(
            name='omset_lainnya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(max_length=255)),
                ('januari', models.IntegerField()),
                ('februari', models.IntegerField()),
                ('maret', models.IntegerField()),
                ('april', models.IntegerField()),
                ('mei', models.IntegerField()),
                ('juni', models.IntegerField()),
                ('juli', models.IntegerField()),
                ('agustus', models.IntegerField()),
                ('september', models.IntegerField()),
                ('oktober', models.IntegerField()),
                ('november', models.IntegerField()),
                ('desember', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Omset Lainnya',
            },
        ),
        migrations.CreateModel(
            name='omset_robotik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(max_length=255)),
                ('januari', models.IntegerField()),
                ('februari', models.IntegerField()),
                ('maret', models.IntegerField()),
                ('april', models.IntegerField()),
                ('mei', models.IntegerField()),
                ('juni', models.IntegerField()),
                ('juli', models.IntegerField()),
                ('agustus', models.IntegerField()),
                ('september', models.IntegerField()),
                ('oktober', models.IntegerField()),
                ('november', models.IntegerField()),
                ('desember', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Omset Robotik',
            },
        ),
        migrations.CreateModel(
            name='omset_tik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(max_length=255)),
                ('januari', models.IntegerField()),
                ('februari', models.IntegerField()),
                ('maret', models.IntegerField()),
                ('april', models.IntegerField()),
                ('mei', models.IntegerField()),
                ('juni', models.IntegerField()),
                ('juli', models.IntegerField()),
                ('agustus', models.IntegerField()),
                ('september', models.IntegerField()),
                ('oktober', models.IntegerField()),
                ('november', models.IntegerField()),
                ('desember', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Omset TIK',
            },
        ),
        migrations.CreateModel(
            name='permintaanSPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('ket', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('ditolak', 'Ditolak'), ('menunggu', 'Menunggu'), ('diterima', 'Diterima')], default='menunggu', max_length=255)),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi'), ('sales', 'Sales')], max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='spt/permintaan')),
            ],
            options={
                'verbose_name_plural': 'Permintaan SPT',
            },
        ),
        migrations.CreateModel(
            name='provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('koordinat', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.CreateModel(
            name='penggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255)),
                ('no_bpjs_kesehatan', models.CharField(max_length=255)),
                ('no_bpjs_naker', models.CharField(max_length=255)),
                ('gaji_pokok', models.IntegerField()),
                ('tunjangan', models.IntegerField()),
                ('THR', models.IntegerField(blank=True, null=True)),
                ('uang_admin', models.IntegerField(blank=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Penggajian',
            },
        ),
        migrations.CreateModel(
            name='pengumuman',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('pesan', models.TextField()),
                ('waktu', models.TimeField()),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi'), ('sales', 'Sales')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pengumuman',
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(max_length=255)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to='apps.sales')),
            ],
            options={
                'verbose_name_plural': 'kegiatan',
            },
        ),
        migrations.CreateModel(
            name='sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('kontak', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jenis', models.CharField(choices=[('tik', 'Tik'), ('robotik', 'Robotik')], max_length=255)),
                ('jenjang', models.ManyToManyField(related_name='sekolah', to='apps.jenjang')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.provinsi')),
            ],
            options={
                'verbose_name_plural': 'Sekolah',
            },
        ),
        migrations.CreateModel(
            name='saran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi')], max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='saran/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saran', to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saran', to='apps.sekolah')),
            ],
            options={
                'verbose_name_plural': 'saran',
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='list_sekolah',
            field=models.ManyToManyField(related_name='sales', to='apps.sekolah'),
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to=settings.AUTH_USER_MODEL)),
                ('list_sekolah', models.ManyToManyField(related_name='produk', to='apps.sekolah')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.CreateModel(
            name='permintaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi')], max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima')], default='menunggu', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='permintaan/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan', to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan', to='apps.sekolah')),
            ],
            options={
                'verbose_name_plural': 'permintaan',
            },
        ),
        migrations.CreateModel(
            name='kunjungan_produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(choices=[('kunjungan', 'Kunjungan'), ('kontak', 'Kontak')], max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai')], default='menunggu', max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('ttd', models.FileField(blank=True, null=True, upload_to='ttd/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_produk', to='apps.produk')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_produk', to='apps.sekolah')),
            ],
            options={
                'verbose_name_plural': 'Kunjungan Produk',
            },
        ),
        migrations.CreateModel(
            name='komplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi')], max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima')], default='menunggu', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='komplain/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komplain', to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komplain', to='apps.sekolah')),
            ],
            options={
                'verbose_name_plural': 'komplain',
            },
        ),
        migrations.CreateModel(
            name='kepsek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kepsek', to='apps.jenjang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kepsek', to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kepsek', to='apps.sekolah')),
            ],
            options={
                'verbose_name_plural': 'Kepsek',
            },
        ),
        migrations.CreateModel(
            name='guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guru', to=settings.AUTH_USER_MODEL)),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guru', to='apps.jenjang')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guru', to='apps.sekolah')),
            ],
            options={
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.jenjang')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.kelas')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.sekolah')),
            ],
            options={
                'verbose_name_plural': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='sptproduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sptproduk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SPT Produk',
            },
        ),
        migrations.CreateModel(
            name='sptsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sptsales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SPT Sales',
            },
        ),
        migrations.CreateModel(
            name='sptteknisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sptteknisi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SPT Teknisi',
            },
        ),
        migrations.CreateModel(
            name='teknisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('list_sekolah', models.ManyToManyField(related_name='teknisi', to='apps.sekolah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teknisi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teknisi',
            },
        ),
        migrations.CreateModel(
            name='kunjungan_teknisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(choices=[('kunjungan rutin', 'Kunjungan Rutin'), ('trouble shooting', 'Trouble Shooting')], max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai')], default='menunggu', max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('ttd', models.FileField(blank=True, null=True, upload_to='ttd/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_teknisi', to='apps.sekolah')),
                ('teknisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_teknisi', to='apps.teknisi')),
            ],
            options={
                'verbose_name_plural': 'Kunjungan Teknisi',
            },
        ),
    ]
