# Generated by Django 5.1.1 on 2024-11-01 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="karyawan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NIK", models.CharField(max_length=255)),
                ("nama", models.CharField(max_length=255)),
                ("alamat", models.CharField(max_length=255)),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("guru profesional", "Guru Profesional"),
                            ("guru bulanan", "Guru Bulanan"),
                            ("guru ekstrakurikuler", "Guru Ekstrakurikuler"),
                            ("korlap", "Korlap"),
                            ("teknisi", "Teknisi"),
                        ],
                        max_length=255,
                    ),
                ),
                ("sekolah", models.CharField(max_length=255)),
                (
                    "jenjang",
                    models.CharField(
                        choices=[
                            ("TK", "TK"),
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                    ),
                ),
                ("gaji_pokok", models.IntegerField(blank=True, null=True)),
                ("tunjangan_nakes", models.IntegerField(blank=True, null=True)),
                ("tunjangan_naker", models.IntegerField(blank=True, null=True)),
                ("uang_admin", models.IntegerField(blank=True, null=True)),
                ("uang_bonus_hari_raya", models.IntegerField(blank=True, null=True)),
                ("bank", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "no_rekening",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Karyawan",
            },
        ),
        migrations.CreateModel(
            name="master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_mou", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nama_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kepala_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_sekolah",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_kepsek",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provinsi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Papua Barat Daya", "Papua Barat Daya"),
                            ("Papua Selatan", "Papua Selatan"),
                            ("Papua Pegunungan", "Papua Pegunungan"),
                            ("Papua Tengah", "Papua Tengah"),
                            ("Papua", "Papua"),
                            ("Papua Barat", "Papua Barat"),
                            ("Maluku Utara", "Maluku Utara"),
                            ("Maluku", "Maluku"),
                            ("Sulawesi Barat", "Sulawesi Barat"),
                            ("Gorontalo", "Gorontalo"),
                            ("Sulawesi Tenggara", "Sulawesi Tenggara"),
                            ("Sulawesi Selatan", "Sulawesi Selatan"),
                            ("Sulawesi Tengah", "Sulawesi Tengah"),
                            ("Sulawesi Utara", "Sulawesi Utara"),
                            ("Kalimantan Utara", "Kalimantan Utara"),
                            ("Kalimantan Timur", "Kalimantan Timur"),
                            ("Kalimantan Selatan", "Kalimantan Selatan"),
                            ("Kalimantan Tengah", "Kalimantan Tengah"),
                            ("Kalimantan Barat", "Kalimantan Barat"),
                            ("Nusa Tenggara Timur", "Nusa Tenggara Timur"),
                            ("Nusa Tenggara Barat", "Nusa Tenggara Barat"),
                            ("Bali", "Bali"),
                            ("Banten", "Banten"),
                            ("Jawa Timur", "Jawa Timur"),
                            ("DI Yogyakarta", "DI Yogyakarta"),
                            ("Jawa Tengah", "Jawa Tengah"),
                            ("Jawa Barat", "Jawa Barat"),
                            ("DKI Jakarta", "DKI Jakarta"),
                            ("Kepulauan Riau", "Kepulauan Riau"),
                            ("Kepulauan Bangka Belitung", "Kepulauan Bangka Belitung"),
                            ("Lampung", "Lampung"),
                            ("Bengkulu", "Bengkulu"),
                            ("Sumatera Selatan", "Sumatera Selatan"),
                            ("Jambi", "Jambi"),
                            ("Riau", "Riau"),
                            ("Sumatera Barat", "Sumatera Barat"),
                            ("Sumatera Utara", "Sumatera Utara"),
                            ("Nanggroe Aceh Darussalam", "Nanggroe Aceh Darussalam"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenjang",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TK", "TK"),
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("awal_kerjasama", models.DateField(blank=True, null=True)),
                ("akhir_kerjasama", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retention", "Retention"),
                            ("existing", "Existing"),
                            ("new", "New"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_kerjasama",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sewa pinjam", "Sewa Pinjam"),
                            ("sewa beli", "Sewa Beli"),
                            ("lisensi", "Lisensi"),
                            ("kontrak pengajaran", "Kontrak Pengajaran"),
                            ("ekstrakulikuler", "Ekstrakulikuler"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_produk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("informatika", "Informatika"),
                            ("smart tk", "Smart TK"),
                            ("robotik", "Robotik"),
                            ("coding", "Coding"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("pembayaran", models.CharField(blank=True, max_length=255, null=True)),
                ("harga_buku", models.CharField(blank=True, max_length=255, null=True)),
                ("jumlah_siswa_tk", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_1", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_2", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_3", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_4", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_5", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_6", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_7", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_8", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_9", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_10", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_11", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_12", models.IntegerField(blank=True, null=True)),
                (
                    "jumlah_siswa_kelas_10_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_11_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_12_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                ("jumlah_komputer", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Master",
            },
        ),
        migrations.CreateModel(
            name="master_ekstrakulikuler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_mou", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nama_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kepala_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_sekolah",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_kepsek",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provinsi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Papua Barat Daya", "Papua Barat Daya"),
                            ("Papua Selatan", "Papua Selatan"),
                            ("Papua Pegunungan", "Papua Pegunungan"),
                            ("Papua Tengah", "Papua Tengah"),
                            ("Papua", "Papua"),
                            ("Papua Barat", "Papua Barat"),
                            ("Maluku Utara", "Maluku Utara"),
                            ("Maluku", "Maluku"),
                            ("Sulawesi Barat", "Sulawesi Barat"),
                            ("Gorontalo", "Gorontalo"),
                            ("Sulawesi Tenggara", "Sulawesi Tenggara"),
                            ("Sulawesi Selatan", "Sulawesi Selatan"),
                            ("Sulawesi Tengah", "Sulawesi Tengah"),
                            ("Sulawesi Utara", "Sulawesi Utara"),
                            ("Kalimantan Utara", "Kalimantan Utara"),
                            ("Kalimantan Timur", "Kalimantan Timur"),
                            ("Kalimantan Selatan", "Kalimantan Selatan"),
                            ("Kalimantan Tengah", "Kalimantan Tengah"),
                            ("Kalimantan Barat", "Kalimantan Barat"),
                            ("Nusa Tenggara Timur", "Nusa Tenggara Timur"),
                            ("Nusa Tenggara Barat", "Nusa Tenggara Barat"),
                            ("Bali", "Bali"),
                            ("Banten", "Banten"),
                            ("Jawa Timur", "Jawa Timur"),
                            ("DI Yogyakarta", "DI Yogyakarta"),
                            ("Jawa Tengah", "Jawa Tengah"),
                            ("Jawa Barat", "Jawa Barat"),
                            ("DKI Jakarta", "DKI Jakarta"),
                            ("Kepulauan Riau", "Kepulauan Riau"),
                            ("Kepulauan Bangka Belitung", "Kepulauan Bangka Belitung"),
                            ("Lampung", "Lampung"),
                            ("Bengkulu", "Bengkulu"),
                            ("Sumatera Selatan", "Sumatera Selatan"),
                            ("Jambi", "Jambi"),
                            ("Riau", "Riau"),
                            ("Sumatera Barat", "Sumatera Barat"),
                            ("Sumatera Utara", "Sumatera Utara"),
                            ("Nanggroe Aceh Darussalam", "Nanggroe Aceh Darussalam"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenjang",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TK", "TK"),
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("awal_kerjasama", models.DateField(blank=True, null=True)),
                ("akhir_kerjasama", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retention", "Retention"),
                            ("existing", "Existing"),
                            ("new", "New"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_kerjasama",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sewa pinjam", "Sewa Pinjam"),
                            ("sewa beli", "Sewa Beli"),
                            ("lisensi", "Lisensi"),
                            ("kontrak pengajaran", "Kontrak Pengajaran"),
                            ("ekstrakulikuler", "Ekstrakulikuler"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_produk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("informatika", "Informatika"),
                            ("smart tk", "Smart TK"),
                            ("robotik", "Robotik"),
                            ("coding", "Coding"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("pembayaran", models.CharField(blank=True, max_length=255, null=True)),
                ("harga_buku", models.CharField(blank=True, max_length=255, null=True)),
                ("jumlah_siswa_tk", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_1", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_2", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_3", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_4", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_5", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_6", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_7", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_8", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_9", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_10", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_11", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_12", models.IntegerField(blank=True, null=True)),
                (
                    "jumlah_siswa_kelas_10_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_11_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_12_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                ("jumlah_komputer", models.IntegerField(blank=True, null=True)),
                (
                    "tipe_sekolah",
                    models.CharField(
                        blank=True,
                        choices=[("robotik", "Robotik"), ("coding", "Coding")],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Master Esktrakulikuler",
            },
        ),
        migrations.CreateModel(
            name="pembayaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_sekolah", models.CharField(max_length=255)),
                (
                    "jenjang",
                    models.CharField(
                        choices=[
                            ("TK", "TK"),
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "jenis_produk",
                    models.CharField(
                        choices=[
                            ("tik", "Tik"),
                            ("hardware & software", "Hardware & Software"),
                            ("buku diginusa", "Buku Diginusa"),
                            ("buku gen", "Buku Gen"),
                            ("robotik", "Robotik"),
                            ("coding", "Coding"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retention", "Retention"),
                            ("existing", "Existing"),
                            ("new", "New"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("januari", models.IntegerField(blank=True, null=True)),
                ("februari", models.IntegerField(blank=True, null=True)),
                ("maret", models.IntegerField(blank=True, null=True)),
                ("april", models.IntegerField(blank=True, null=True)),
                ("mei", models.IntegerField(blank=True, null=True)),
                ("juni", models.IntegerField(blank=True, null=True)),
                ("juli", models.IntegerField(blank=True, null=True)),
                ("agustus", models.IntegerField(blank=True, null=True)),
                ("september", models.IntegerField(blank=True, null=True)),
                ("oktober", models.IntegerField(blank=True, null=True)),
                ("november", models.IntegerField(blank=True, null=True)),
                ("desember", models.IntegerField(blank=True, null=True)),
                (
                    "tipe_pembayaran",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("omset", "Omset"),
                            ("pemasukan", "Pemasukan"),
                            ("pengeluaran", "Pengeluaran"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pembayaran",
            },
        ),
        migrations.CreateModel(
            name="komplain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("keterangan", models.CharField(max_length=255)),
                (
                    "kategori",
                    models.CharField(
                        choices=[("produk", "Produk"), ("teknisi", "Teknisi")],
                        max_length=255,
                    ),
                ),
                ("tanggal", models.DateField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("menunggu", "Menunggu"), ("diterima", "Diterima")],
                        default="menunggu",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="komplain/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komplain",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sekolah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komplain",
                        to="apps.master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "komplain",
            },
        ),
        migrations.CreateModel(
            name="kepsek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("telp", models.CharField(max_length=255)),
                (
                    "jenjang",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TK", "TK"),
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kepsek",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sekolah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kepsek",
                        to="apps.master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kepsek",
            },
        ),
        migrations.CreateModel(
            name="history_adendum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_mou", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nama_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kepala_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_sekolah",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_kepsek",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provinsi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Papua Barat Daya", "Papua Barat Daya"),
                            ("Papua Selatan", "Papua Selatan"),
                            ("Papua Pegunungan", "Papua Pegunungan"),
                            ("Papua Tengah", "Papua Tengah"),
                            ("Papua", "Papua"),
                            ("Papua Barat", "Papua Barat"),
                            ("Maluku Utara", "Maluku Utara"),
                            ("Maluku", "Maluku"),
                            ("Sulawesi Barat", "Sulawesi Barat"),
                            ("Gorontalo", "Gorontalo"),
                            ("Sulawesi Tenggara", "Sulawesi Tenggara"),
                            ("Sulawesi Selatan", "Sulawesi Selatan"),
                            ("Sulawesi Tengah", "Sulawesi Tengah"),
                            ("Sulawesi Utara", "Sulawesi Utara"),
                            ("Kalimantan Utara", "Kalimantan Utara"),
                            ("Kalimantan Timur", "Kalimantan Timur"),
                            ("Kalimantan Selatan", "Kalimantan Selatan"),
                            ("Kalimantan Tengah", "Kalimantan Tengah"),
                            ("Kalimantan Barat", "Kalimantan Barat"),
                            ("Nusa Tenggara Timur", "Nusa Tenggara Timur"),
                            ("Nusa Tenggara Barat", "Nusa Tenggara Barat"),
                            ("Bali", "Bali"),
                            ("Banten", "Banten"),
                            ("Jawa Timur", "Jawa Timur"),
                            ("DI Yogyakarta", "DI Yogyakarta"),
                            ("Jawa Tengah", "Jawa Tengah"),
                            ("Jawa Barat", "Jawa Barat"),
                            ("DKI Jakarta", "DKI Jakarta"),
                            ("Kepulauan Riau", "Kepulauan Riau"),
                            ("Kepulauan Bangka Belitung", "Kepulauan Bangka Belitung"),
                            ("Lampung", "Lampung"),
                            ("Bengkulu", "Bengkulu"),
                            ("Sumatera Selatan", "Sumatera Selatan"),
                            ("Jambi", "Jambi"),
                            ("Riau", "Riau"),
                            ("Sumatera Barat", "Sumatera Barat"),
                            ("Sumatera Utara", "Sumatera Utara"),
                            ("Nanggroe Aceh Darussalam", "Nanggroe Aceh Darussalam"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenjang",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TK", "TK"),
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("awal_kerjasama", models.DateField(blank=True, null=True)),
                ("akhir_kerjasama", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retention", "Retention"),
                            ("existing", "Existing"),
                            ("new", "New"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_kerjasama",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sewa pinjam", "Sewa Pinjam"),
                            ("sewa beli", "Sewa Beli"),
                            ("lisensi", "Lisensi"),
                            ("kontrak pengajaran", "Kontrak Pengajaran"),
                            ("ekstrakulikuler", "Ekstrakulikuler"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_produk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("informatika", "Informatika"),
                            ("smart tk", "Smart TK"),
                            ("robotik", "Robotik"),
                            ("coding", "Coding"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("pembayaran", models.CharField(blank=True, max_length=255, null=True)),
                ("harga_buku", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_tk", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_1", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_2", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_3", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_4", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_5", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_6", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_7", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_8", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_9", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_10", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_11", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_12", models.IntegerField(blank=True, null=True)),
                (
                    "jumlah_siswa_kelas_10_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_11_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_12_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                ("jumlah_komputer", models.IntegerField(blank=True, null=True)),
                ("tanggal_adendum", models.DateField(blank=True, null=True)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_adendum",
                        to="apps.master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "History Adendum",
            },
        ),
        migrations.CreateModel(
            name="guru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("telp", models.CharField(max_length=255)),
                (
                    "jenjang",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TK", "TK"),
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guru",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sekolah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guru",
                        to="apps.master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Guru",
            },
        ),
        migrations.CreateModel(
            name="history_adendum_ekskul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_mou", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nama_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kepala_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_sekolah",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_kepsek",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provinsi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Papua Barat Daya", "Papua Barat Daya"),
                            ("Papua Selatan", "Papua Selatan"),
                            ("Papua Pegunungan", "Papua Pegunungan"),
                            ("Papua Tengah", "Papua Tengah"),
                            ("Papua", "Papua"),
                            ("Papua Barat", "Papua Barat"),
                            ("Maluku Utara", "Maluku Utara"),
                            ("Maluku", "Maluku"),
                            ("Sulawesi Barat", "Sulawesi Barat"),
                            ("Gorontalo", "Gorontalo"),
                            ("Sulawesi Tenggara", "Sulawesi Tenggara"),
                            ("Sulawesi Selatan", "Sulawesi Selatan"),
                            ("Sulawesi Tengah", "Sulawesi Tengah"),
                            ("Sulawesi Utara", "Sulawesi Utara"),
                            ("Kalimantan Utara", "Kalimantan Utara"),
                            ("Kalimantan Timur", "Kalimantan Timur"),
                            ("Kalimantan Selatan", "Kalimantan Selatan"),
                            ("Kalimantan Tengah", "Kalimantan Tengah"),
                            ("Kalimantan Barat", "Kalimantan Barat"),
                            ("Nusa Tenggara Timur", "Nusa Tenggara Timur"),
                            ("Nusa Tenggara Barat", "Nusa Tenggara Barat"),
                            ("Bali", "Bali"),
                            ("Banten", "Banten"),
                            ("Jawa Timur", "Jawa Timur"),
                            ("DI Yogyakarta", "DI Yogyakarta"),
                            ("Jawa Tengah", "Jawa Tengah"),
                            ("Jawa Barat", "Jawa Barat"),
                            ("DKI Jakarta", "DKI Jakarta"),
                            ("Kepulauan Riau", "Kepulauan Riau"),
                            ("Kepulauan Bangka Belitung", "Kepulauan Bangka Belitung"),
                            ("Lampung", "Lampung"),
                            ("Bengkulu", "Bengkulu"),
                            ("Sumatera Selatan", "Sumatera Selatan"),
                            ("Jambi", "Jambi"),
                            ("Riau", "Riau"),
                            ("Sumatera Barat", "Sumatera Barat"),
                            ("Sumatera Utara", "Sumatera Utara"),
                            ("Nanggroe Aceh Darussalam", "Nanggroe Aceh Darussalam"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenjang",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TK", "TK"),
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("awal_kerjasama", models.DateField(blank=True, null=True)),
                ("akhir_kerjasama", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retention", "Retention"),
                            ("existing", "Existing"),
                            ("new", "New"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_kerjasama",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sewa pinjam", "Sewa Pinjam"),
                            ("sewa beli", "Sewa Beli"),
                            ("lisensi", "Lisensi"),
                            ("kontrak pengajaran", "Kontrak Pengajaran"),
                            ("ekstrakulikuler", "Ekstrakulikuler"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_produk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("informatika", "Informatika"),
                            ("smart tk", "Smart TK"),
                            ("robotik", "Robotik"),
                            ("coding", "Coding"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("pembayaran", models.CharField(blank=True, max_length=255, null=True)),
                ("harga_buku", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_tk", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_1", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_2", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_3", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_4", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_5", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_6", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_7", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_8", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_9", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_10", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_11", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_12", models.IntegerField(blank=True, null=True)),
                (
                    "jumlah_siswa_kelas_10_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_11_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_12_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                ("jumlah_komputer", models.IntegerField(blank=True, null=True)),
                (
                    "tipe_sekolah",
                    models.CharField(
                        blank=True,
                        choices=[("robotik", "Robotik"), ("coding", "Coding")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("tanggal_adendum", models.DateField(blank=True, null=True)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_adendum_ekskul",
                        to="apps.master_ekstrakulikuler",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "History Adendum Ekstrakulikuler",
            },
        ),
        migrations.CreateModel(
            name="penggajian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "no_bpjs_kesehatan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "no_bpjs_naker",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gaji_pokok", models.IntegerField(blank=True, null=True)),
                ("uang_admin", models.IntegerField(blank=True, null=True)),
                ("januari", models.IntegerField(blank=True, null=True)),
                ("februari", models.IntegerField(blank=True, null=True)),
                ("maret", models.IntegerField(blank=True, null=True)),
                ("april", models.IntegerField(blank=True, null=True)),
                ("mei", models.IntegerField(blank=True, null=True)),
                ("juni", models.IntegerField(blank=True, null=True)),
                ("juli", models.IntegerField(blank=True, null=True)),
                ("agustus", models.IntegerField(blank=True, null=True)),
                ("september", models.IntegerField(blank=True, null=True)),
                ("oktober", models.IntegerField(blank=True, null=True)),
                ("november", models.IntegerField(blank=True, null=True)),
                ("desember", models.IntegerField(blank=True, null=True)),
                ("tahun", models.IntegerField(blank=True, null=True)),
                (
                    "karyawan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.karyawan"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Penggajian",
            },
        ),
        migrations.CreateModel(
            name="pengumuman",
            fields=[
                ("id_chat", models.AutoField(primary_key=True, serialize=False)),
                ("pesan", models.TextField(max_length=255)),
                ("waktu", models.TimeField()),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("produk", "Produk"),
                            ("teknisi", "Teknisi"),
                            ("sales", "Sales"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pengumuman",
            },
        ),
        migrations.CreateModel(
            name="permintaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("keterangan", models.CharField(max_length=255)),
                (
                    "kategori",
                    models.CharField(
                        choices=[("produk", "Produk"), ("teknisi", "Teknisi")],
                        max_length=255,
                    ),
                ),
                ("tanggal", models.DateField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("menunggu", "Menunggu"), ("diterima", "Diterima")],
                        default="menunggu",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="permintaan/"),
                ),
                (
                    "sekolah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permintaan",
                        to="apps.master",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permintaan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "permintaan",
            },
        ),
        migrations.CreateModel(
            name="permintaanSPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("ket", models.TextField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ditolak", "Ditolak"),
                            ("menunggu", "Menunggu"),
                            ("diterima", "Diterima"),
                        ],
                        default="menunggu",
                        max_length=255,
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("produk", "Produk"),
                            ("teknisi", "Teknisi"),
                            ("sales", "Sales"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="spt/permintaan"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Permintaan SPT",
            },
        ),
        migrations.CreateModel(
            name="produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("telp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "produk",
            },
        ),
        migrations.AddField(
            model_name="master_ekstrakulikuler",
            name="user_produk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master_ekstrakulikuler",
                to="apps.produk",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="user_produk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master",
                to="apps.produk",
            ),
        ),
        migrations.CreateModel(
            name="kunjungan_produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        choices=[("kunjungan", "Kunjungan"), ("kontak", "Kontak")],
                        max_length=255,
                    ),
                ),
                ("deskripsi", models.CharField(max_length=255)),
                (
                    "geolocation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("menunggu", "Menunggu"), ("selesai", "Selesai")],
                        default="menunggu",
                        max_length=255,
                    ),
                ),
                ("tanggal", models.DateField(max_length=255)),
                ("ttd", models.FileField(blank=True, null=True, upload_to="ttd/")),
                (
                    "nama_kepsek_atau_guru",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sekolah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kunjungan_produk",
                        to="apps.master",
                    ),
                ),
                (
                    "sekolah_ekskul",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kunjungan_produk",
                        to="apps.master_ekstrakulikuler",
                    ),
                ),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kunjungan_produk",
                        to="apps.produk",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kunjungan Produk",
            },
        ),
        migrations.CreateModel(
            name="sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("telp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.AddField(
            model_name="master",
            name="user_sales",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master",
                to="apps.sales",
            ),
        ),
        migrations.CreateModel(
            name="kegiatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        choices=[
                            ("Kunjungan Sekolah Baru", "Kunjungan Sekolah Baru"),
                            (
                                "Kunjungan Sekolah Existing",
                                "Kunjungan Sekolah Existing",
                            ),
                            ("Kunjungan Sekolah Event", "Kunjungan Sekolah Event"),
                            ("Pertemuan Client", "Pertemuan Client"),
                        ],
                        max_length=255,
                    ),
                ),
                ("deskripsi", models.TextField(max_length=255)),
                ("tanggal", models.DateField(blank=True, null=True)),
                ("sekolah", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kegiatan",
                        to="apps.sales",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "kegiatan",
            },
        ),
        migrations.CreateModel(
            name="saran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("keterangan", models.CharField(max_length=255)),
                (
                    "kategori",
                    models.CharField(
                        choices=[("produk", "Produk"), ("teknisi", "Teknisi")],
                        max_length=255,
                    ),
                ),
                ("tanggal", models.DateField(max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="saran/")),
                (
                    "sekolah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saran",
                        to="apps.master",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saran",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "saran",
            },
        ),
        migrations.CreateModel(
            name="sptproduk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sptproduk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SPT Produk",
            },
        ),
        migrations.CreateModel(
            name="sptsales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sptsales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SPT Sales",
            },
        ),
        migrations.CreateModel(
            name="sptteknisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sptteknisi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SPT Teknisi",
            },
        ),
        migrations.CreateModel(
            name="teknisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("telp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teknisi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teknisi",
            },
        ),
        migrations.AddField(
            model_name="master",
            name="user_teknisi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master",
                to="apps.teknisi",
            ),
        ),
        migrations.CreateModel(
            name="kunjungan_teknisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("trouble shooting", "Trouble Shooting"),
                        ],
                        max_length=255,
                    ),
                ),
                ("deskripsi", models.CharField(max_length=255)),
                (
                    "geolocation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("menunggu", "Menunggu"), ("selesai", "Selesai")],
                        default="menunggu",
                        max_length=255,
                    ),
                ),
                ("tanggal", models.DateField(max_length=255)),
                ("ttd", models.FileField(blank=True, null=True, upload_to="ttd/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sekolah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kunjungan_teknisi",
                        to="apps.master",
                    ),
                ),
                (
                    "teknisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kunjungan_teknisi",
                        to="apps.teknisi",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kunjungan Teknisi",
            },
        ),
    ]
