# Generated by Django 5.1.1 on 2024-10-21 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIK', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('guru profesional', 'Guru Profesional'), ('guru bulanan', 'Guru Bulanan'), ('guru ekstrakurikuler', 'Guru Ekstrakurikuler'), ('korlap', 'Korlap'), ('teknisi', 'Teknisi')], max_length=255)),
                ('sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Karyawan',
            },
        ),
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_mou', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_yayasan', models.CharField(blank=True, max_length=255, null=True)),
                ('kepala_yayasan', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_sekolah', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_kepsek', models.CharField(blank=True, max_length=255, null=True)),
                ('jenjang', models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=255, null=True)),
                ('awal_kerjasama', models.DateField(blank=True, null=True)),
                ('akhir_kerjasama', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('retention', 'Retention'), ('existing', 'Existing'), ('new', 'New')], max_length=255, null=True)),
                ('jenis_kerjasama', models.CharField(blank=True, choices=[('sewa pinjam', 'Sewa Pinjam'), ('sewa beli', 'Sewa Beli'), ('lisensi', 'Lisensi'), ('kontrak pengajaran', 'Kontrak Pengajaran'), ('ekstrakulikuler', 'Ekstrakulikuler')], max_length=255, null=True)),
                ('jenis_produk', models.CharField(blank=True, choices=[('informatika', 'Informatika'), ('smart tk', 'Smart TK'), ('robotik', 'Robotik'), ('coding', 'Coding')], max_length=255, null=True)),
                ('pembayaran', models.CharField(blank=True, max_length=255, null=True)),
                ('harga_buku', models.CharField(blank=True, max_length=255, null=True)),
                ('jumlah_siswa_kelas_1', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_2', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_3', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_4', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_5', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_6', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_7', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_8', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_9', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_10', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_11', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_12', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_10_smk', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_11_smk', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_12_smk', models.IntegerField(blank=True, null=True)),
                ('jumlah_komputer', models.IntegerField(blank=True, null=True)),
                ('tipe_sekolah', models.CharField(blank=True, choices=[('tik', 'Tik'), ('robotik', 'Robotik')], max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Master',
            },
        ),
        migrations.CreateModel(
            name='pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=255)),
                ('jenjang', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=255)),
                ('jenis_produk', models.CharField(choices=[('tik', 'Tik'), ('hardware & software', 'Hardware & Software'), ('buku diginusa', 'Buku Diginusa'), ('buku gen', 'Buku Gen'), ('robotik', 'Robotik'), ('coding', 'Coding'), ('lainnya', 'Lainnya')], max_length=255)),
                ('status', models.CharField(blank=True, choices=[('retention', 'Retention'), ('existing', 'Existing'), ('new', 'New')], max_length=255, null=True)),
                ('januari', models.IntegerField(blank=True, null=True)),
                ('februari', models.IntegerField(blank=True, null=True)),
                ('maret', models.IntegerField(blank=True, null=True)),
                ('april', models.IntegerField(blank=True, null=True)),
                ('mei', models.IntegerField(blank=True, null=True)),
                ('juni', models.IntegerField(blank=True, null=True)),
                ('juli', models.IntegerField(blank=True, null=True)),
                ('agustus', models.IntegerField(blank=True, null=True)),
                ('september', models.IntegerField(blank=True, null=True)),
                ('oktober', models.IntegerField(blank=True, null=True)),
                ('november', models.IntegerField(blank=True, null=True)),
                ('desember', models.IntegerField(blank=True, null=True)),
                ('tipe_pembayaran', models.CharField(blank=True, choices=[('omset', 'Omset'), ('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('koordinat', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.CreateModel(
            name='komplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi')], max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima')], default='menunggu', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='komplain/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komplain', to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komplain', to='apps.master')),
            ],
            options={
                'verbose_name_plural': 'komplain',
            },
        ),
        migrations.CreateModel(
            name='kepsek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('jenjang', models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kepsek', to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kepsek', to='apps.master')),
            ],
            options={
                'verbose_name_plural': 'Kepsek',
            },
        ),
        migrations.CreateModel(
            name='guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('jenjang', models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guru', to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guru', to='apps.master')),
            ],
            options={
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='penggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('no_bpjs_kesehatan', models.CharField(blank=True, max_length=255, null=True)),
                ('no_bpjs_naker', models.CharField(blank=True, max_length=255, null=True)),
                ('gaji_pokok', models.IntegerField(blank=True, null=True)),
                ('tunjangan', models.IntegerField(blank=True, null=True)),
                ('THR', models.IntegerField(blank=True, null=True)),
                ('uang_admin', models.IntegerField(blank=True, null=True)),
                ('januari', models.IntegerField(blank=True, null=True)),
                ('februari', models.IntegerField(blank=True, null=True)),
                ('maret', models.IntegerField(blank=True, null=True)),
                ('april', models.IntegerField(blank=True, null=True)),
                ('mei', models.IntegerField(blank=True, null=True)),
                ('juni', models.IntegerField(blank=True, null=True)),
                ('juli', models.IntegerField(blank=True, null=True)),
                ('agustus', models.IntegerField(blank=True, null=True)),
                ('september', models.IntegerField(blank=True, null=True)),
                ('oktober', models.IntegerField(blank=True, null=True)),
                ('november', models.IntegerField(blank=True, null=True)),
                ('desember', models.IntegerField(blank=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Penggajian',
            },
        ),
        migrations.CreateModel(
            name='pengumuman',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('pesan', models.TextField(max_length=255)),
                ('waktu', models.TimeField()),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi'), ('sales', 'Sales')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pengumuman',
            },
        ),
        migrations.CreateModel(
            name='permintaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi')], max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima')], default='menunggu', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='permintaan/')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan', to='apps.master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'permintaan',
            },
        ),
        migrations.CreateModel(
            name='permintaanSPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('ket', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('ditolak', 'Ditolak'), ('menunggu', 'Menunggu'), ('diterima', 'Diterima')], default='menunggu', max_length=255)),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi'), ('sales', 'Sales')], max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='spt/permintaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Permintaan SPT',
            },
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('list_sekolah', models.ManyToManyField(blank=True, null=True, related_name='produk', to='apps.master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'produk',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='user_produk',
            field=models.ManyToManyField(blank=True, related_name='master', to='apps.produk'),
        ),
        migrations.CreateModel(
            name='kunjungan_produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(choices=[('kunjungan', 'Kunjungan'), ('kontak', 'Kontak')], max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai')], default='menunggu', max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('ttd', models.FileField(blank=True, null=True, upload_to='ttd/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_produk', to='apps.master')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_produk', to='apps.produk')),
            ],
            options={
                'verbose_name_plural': 'Kunjungan Produk',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.provinsi'),
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('list_sekolah', models.ManyToManyField(blank=True, null=True, related_name='sales', to='apps.master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='user_sales',
            field=models.ManyToManyField(blank=True, related_name='master', to='apps.sales'),
        ),
        migrations.CreateModel(
            name='kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(max_length=255)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to='apps.sales')),
            ],
            options={
                'verbose_name_plural': 'kegiatan',
            },
        ),
        migrations.CreateModel(
            name='saran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('produk', 'Produk'), ('teknisi', 'Teknisi')], max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='saran/')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saran', to='apps.master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saran', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'saran',
            },
        ),
        migrations.CreateModel(
            name='sptproduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sptproduk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SPT Produk',
            },
        ),
        migrations.CreateModel(
            name='sptsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sptsales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SPT Sales',
            },
        ),
        migrations.CreateModel(
            name='sptteknisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sptteknisi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SPT Teknisi',
            },
        ),
        migrations.CreateModel(
            name='teknisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('list_sekolah', models.ManyToManyField(blank=True, null=True, related_name='teknisi', to='apps.master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teknisi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teknisi',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='user_teknisi',
            field=models.ManyToManyField(blank=True, related_name='master', to='apps.teknisi'),
        ),
        migrations.CreateModel(
            name='kunjungan_teknisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(choices=[('kunjungan rutin', 'Kunjungan Rutin'), ('trouble shooting', 'Trouble Shooting')], max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai')], default='menunggu', max_length=255)),
                ('tanggal', models.DateField(max_length=255)),
                ('ttd', models.FileField(blank=True, null=True, upload_to='ttd/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_teknisi', to='apps.master')),
                ('teknisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_teknisi', to='apps.teknisi')),
            ],
            options={
                'verbose_name_plural': 'Kunjungan Teknisi',
            },
        ),
        migrations.CreateModel(
            name='history_adendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_mou', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_yayasan', models.CharField(blank=True, max_length=255, null=True)),
                ('kepala_yayasan', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_sekolah', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_kepsek', models.CharField(blank=True, max_length=255, null=True)),
                ('jenjang', models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=255, null=True)),
                ('awal_kerjasama', models.DateField(blank=True, null=True)),
                ('akhir_kerjasama', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('retention', 'Retention'), ('existing', 'Existing'), ('new', 'New')], max_length=255, null=True)),
                ('jenis_kerjasama', models.CharField(blank=True, choices=[('sewa pinjam', 'Sewa Pinjam'), ('sewa beli', 'Sewa Beli'), ('lisensi', 'Lisensi'), ('kontrak pengajaran', 'Kontrak Pengajaran'), ('ekstrakulikuler', 'Ekstrakulikuler')], max_length=255, null=True)),
                ('jenis_produk', models.CharField(blank=True, choices=[('informatika', 'Informatika'), ('smart tk', 'Smart TK'), ('robotik', 'Robotik'), ('coding', 'Coding')], max_length=255, null=True)),
                ('pembayaran', models.CharField(blank=True, max_length=255, null=True)),
                ('harga_buku', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_1', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_2', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_3', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_4', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_5', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_6', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_7', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_8', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_9', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_10', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_11', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_12', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_10_smk', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_11_smk', models.IntegerField(blank=True, null=True)),
                ('jumlah_siswa_kelas_12_smk', models.IntegerField(blank=True, null=True)),
                ('jumlah_komputer', models.IntegerField(blank=True, null=True)),
                ('tipe_sekolah', models.CharField(blank=True, choices=[('tik', 'Tik'), ('robotik', 'Robotik')], max_length=255, null=True)),
                ('tanggal_adendum', models.DateField(blank=True, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_adendum', to='apps.master')),
                ('user_produk', models.ManyToManyField(blank=True, related_name='history_adendum', to='apps.produk')),
                ('provinsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.provinsi')),
                ('user_sales', models.ManyToManyField(blank=True, related_name='history_adendum', to='apps.sales')),
                ('user_teknisi', models.ManyToManyField(blank=True, related_name='history_adendum', to='apps.teknisi')),
            ],
            options={
                'verbose_name_plural': 'History Adendum',
            },
        ),
    ]
