# Generated by Django 5.1.1 on 2024-10-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='gaji_pokok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='no_rekening',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='tunjangan_naker',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='tunjangan_nakes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='uang_admin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='uang_bonus_hari_raya',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
