# Generated by Django 5.1.1 on 2024-10-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_karyawan_bank_karyawan_gaji_pokok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='user_produk',
        ),
        migrations.RemoveField(
            model_name='master',
            name='user_sales',
        ),
        migrations.RemoveField(
            model_name='master',
            name='user_teknisi',
        ),
    ]
