# Generated by Django 5.1.1 on 2024-11-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_master_user_produk_alter_master_user_sales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history_adendum",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="file_history_adendum/"
            ),
        ),
        migrations.AddField(
            model_name="history_adendum_ekskul",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="file_history_adendum_ekskul/"
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="file_master/"),
        ),
        migrations.AddField(
            model_name="master_ekstrakulikuler",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="file_master_ekstrakulikuler/"
            ),
        ),
    ]
