# Generated by Django 5.1.1 on 2024-11-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_history_adendum_file_history_adendum_ekskul_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permintaanspt",
            name="alasan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
