# Generated by Django 5.1.1 on 2024-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_master_user_produk_remove_master_user_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='judul',
            field=models.CharField(choices=[('Kunjungan Sekolah Baru', 'Kunjungan Sekolah Baru'), ('Kunjungan Sekolah Existing', 'Kunjungan Sekolah Existing'), ('Kunjungan Sekolah Event', 'Kunjungan Sekolah Event'), ('Pertemuan Client', 'Pertemuan Client')], max_length=255),
        ),
    ]
