# Generated by Django 5.1.1 on 2024-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_permintaanspt_alasan"),
    ]

    operations = [
        migrations.AddField(
            model_name="kunjungan_teknisi",
            name="nama_kepsek_atau_guru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="kunjungan_teknisi",
            name="sekolah",
        ),
        migrations.AddField(
            model_name="kunjungan_teknisi",
            name="sekolah",
            field=models.ManyToManyField(
                related_name="kunjungan_teknisi", to="apps.master"
            ),
        ),
    ]
