# Generated by Django 5.1.1 on 2024-11-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_kunjungan_teknisi_nama_kepsek_atau_guru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kunjungan_teknisi",
            name="judul",
            field=models.CharField(
                choices=[
                    ("maintenance", "Maintenance"),
                    ("trouble shooting", "Trouble Shooting"),
                    ("remote", "Remote"),
                ],
                max_length=255,
            ),
        ),
    ]
