# Generated by Django 5.1.1 on 2024-10-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_kegiatan_sekolah"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kunjungan_teknisi",
            name="judul",
            field=models.CharField(
                choices=[
                    ("maintenance", "Maintenance"),
                    ("trouble shooting", "Trouble Shooting"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="list_sekolah",
            field=models.ManyToManyField(related_name="produk", to="apps.master"),
        ),
        migrations.AlterField(
            model_name="sales",
            name="list_sekolah",
            field=models.ManyToManyField(related_name="sales", to="apps.master"),
        ),
        migrations.AlterField(
            model_name="teknisi",
            name="list_sekolah",
            field=models.ManyToManyField(related_name="teknisi", to="apps.master"),
        ),
    ]
