# Generated by Django 5.1.1 on 2024-11-05 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_alter_kunjungan_teknisi_judul"),
    ]

    operations = [
        migrations.CreateModel(
            name="kegiatan_produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        choices=[
                            ("Mengajar", "Mengajar"),
                            ("Training", "Training"),
                            ("Presentasi", "Presentasi"),
                            ("Event", "Event"),
                            ("Pembicara", "Pembicara"),
                        ],
                        max_length=255,
                    ),
                ),
                ("deskripsi", models.TextField(max_length=255)),
                ("tanggal", models.DateField(blank=True, null=True)),
                ("sekolah", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kegiatan_produk",
                        to="apps.produk",
                    ),
                ),
            ],
        ),
    ]
