# Generated by Django 5.1.1 on 2024-10-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_alter_kunjungan_teknisi_judul_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kegiatan",
            name="sekolah",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
