# Generated by Django 5.1.1 on 2024-11-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_kegiatan_produk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kegiatan_produk",
            options={"verbose_name_plural": "Kegiatan Produk"},
        ),
        migrations.AddField(
            model_name="pengumuman",
            name="nama",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
