# Generated by Django 5.1.1 on 2024-11-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_alter_kegiatan_produk_options_pengumuman_nama"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pembayaran",
            old_name="agustus",
            new_name="agustus_by_cash",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="april",
            new_name="agustus_by_omset",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="desember",
            new_name="april_by_cash",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="februari",
            new_name="april_by_omset",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="januari",
            new_name="desember_by_cash",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="juli",
            new_name="desember_by_omset",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="juni",
            new_name="februari_by_cash",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="maret",
            new_name="februari_by_omset",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="mei",
            new_name="januari_by_cash",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="november",
            new_name="januari_by_omset",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="oktober",
            new_name="juli_by_cash",
        ),
        migrations.RenameField(
            model_name="pembayaran",
            old_name="september",
            new_name="juli_by_omset",
        ),
        migrations.RemoveField(
            model_name="pembayaran",
            name="tipe_pembayaran",
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="juni_by_cash",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="juni_by_omset",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="maret_by_cash",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="maret_by_omset",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="mei_by_cash",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="mei_by_omset",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="november_by_cash",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="november_by_omset",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="oktober_by_cash",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="oktober_by_omset",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="september_by_cash",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="september_by_omset",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pembayaran",
            name="jenis_produk",
            field=models.CharField(
                choices=[
                    ("tik", "TIK"),
                    ("hardware & software", "Hardware & Software"),
                    ("buku diginusa", "Buku Diginusa"),
                    ("buku gen", "Buku Gen"),
                    ("robotik", "Robotik"),
                    ("coding", "Coding"),
                    ("lainnya", "Lainnya"),
                ],
                max_length=255,
            ),
        ),
    ]
