# Generated by Django 5.1.1 on 2024-10-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_remove_master_tipe_sekolah_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produk",
            name="list_sekolah_ekstrakulikuler",
            field=models.ManyToManyField(
                related_name="produk", to="apps.master_ekstrakulikuler"
            ),
        ),
    ]
