# Generated by Django 5.1.1 on 2024-11-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_rename_agustus_pembayaran_agustus_by_cash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pembayaran",
            name="jenis_produk",
            field=models.CharField(
                choices=[
                    ("tik", "TIK"),
                    ("hardware & software", "Hardware & Software"),
                    ("buku diginusa", "Buku Diginusa"),
                    ("buku gen", "Buku Gen"),
                    ("robotik", "Robotik"),
                    ("coding", "Coding"),
                    ("kontrak jasa service", "Kontrak Jasa Service"),
                    ("lainnya", "Lainnya"),
                ],
                max_length=255,
            ),
        ),
    ]
