# Generated by Django 5.1.1 on 2024-10-28 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0010_remove_history_adendum_user_produk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kunjungan_produk",
            name="sekolah_ekskul",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kunjungan_produk",
                to="apps.master_ekstrakulikuler",
            ),
        ),
        migrations.AlterField(
            model_name="kunjungan_produk",
            name="sekolah",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kunjungan_produk",
                to="apps.master",
            ),
        ),
    ]
