# Generated by Django 5.1.1 on 2024-11-19 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0010_alter_pembayaran_jenis_produk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pengeluaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        choices=[
                            ("DLK", "DLK"),
                            ("reimburse", "Reimburse"),
                            ("entertaint", "Entertaint"),
                        ],
                        max_length=255,
                    ),
                ),
                ("jumlah", models.IntegerField(blank=True, null=True)),
                ("tanggal", models.DateField(blank=True, null=True)),
                (
                    "bukti_pengeluaran",
                    models.FileField(
                        blank=True, null=True, upload_to="bukti_pengeluaran/"
                    ),
                ),
                ("kategori", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pengeluaran",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
