# Generated by Django 5.1.1 on 2024-12-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0011_pengeluaran"),
    ]

    operations = [
        migrations.AddField(
            model_name="pengeluaran",
            name="keterangan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pengeluaran",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("Produk", "Produk"),
                    ("Teknisi", "Teknisi"),
                    ("Sales", "Sales"),
                ],
                max_length=255,
            ),
        ),
    ]
