# Generated by Django 5.1.1 on 2024-10-29 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0012_remove_penggajian_thr_remove_penggajian_tunjangan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history_adendum",
            name="tipe_sekolah",
        ),
        migrations.AlterField(
            model_name="master_ekstrakulikuler",
            name="tipe_sekolah",
            field=models.CharField(
                blank=True,
                choices=[("robotik", "Robotik"), ("coding", "Coding")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="history_adendum_ekskul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_mou", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nama_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kepala_yayasan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_sekolah",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_kepsek",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "jenjang",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("SMK", "SMK"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("awal_kerjasama", models.DateField(blank=True, null=True)),
                ("akhir_kerjasama", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retention", "Retention"),
                            ("existing", "Existing"),
                            ("new", "New"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_kerjasama",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sewa pinjam", "Sewa Pinjam"),
                            ("sewa beli", "Sewa Beli"),
                            ("lisensi", "Lisensi"),
                            ("kontrak pengajaran", "Kontrak Pengajaran"),
                            ("ekstrakulikuler", "Ekstrakulikuler"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "jenis_produk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("informatika", "Informatika"),
                            ("smart tk", "Smart TK"),
                            ("robotik", "Robotik"),
                            ("coding", "Coding"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("pembayaran", models.CharField(blank=True, max_length=255, null=True)),
                ("harga_buku", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_1", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_2", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_3", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_4", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_5", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_6", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_7", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_8", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_9", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_10", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_11", models.IntegerField(blank=True, null=True)),
                ("jumlah_siswa_kelas_12", models.IntegerField(blank=True, null=True)),
                (
                    "jumlah_siswa_kelas_10_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_11_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "jumlah_siswa_kelas_12_smk",
                    models.IntegerField(blank=True, null=True),
                ),
                ("jumlah_komputer", models.IntegerField(blank=True, null=True)),
                (
                    "tipe_sekolah",
                    models.CharField(
                        blank=True,
                        choices=[("robotik", "Robotik"), ("coding", "Coding")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("tanggal_adendum", models.DateField(blank=True, null=True)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_adendum_ekskul",
                        to="apps.master_ekstrakulikuler",
                    ),
                ),
                (
                    "provinsi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.provinsi",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "History Adendum Ekstrakulikuler",
            },
        ),
    ]
