# Generated by Django 5.1.1 on 2024-12-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0012_pengeluaran_keterangan_alter_pengeluaran_kategori"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="master",
            name="status",
        ),
    ]
