# Generated by Django 5.1.1 on 2024-10-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0014_penggajian_tahun"),
    ]

    operations = [
        migrations.AddField(
            model_name="history_adendum",
            name="jumlah_siswa_tk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="history_adendum_ekskul",
            name="jumlah_siswa_tk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="master",
            name="jumlah_siswa_tk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="master_ekstrakulikuler",
            name="jumlah_siswa_tk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guru",
            name="jenjang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TK", "TK"),
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("SMK", "SMK"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="history_adendum",
            name="jenjang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TK", "TK"),
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("SMK", "SMK"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="history_adendum_ekskul",
            name="jenjang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TK", "TK"),
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("SMK", "SMK"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="karyawan",
            name="jenjang",
            field=models.CharField(
                choices=[
                    ("TK", "TK"),
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("SMK", "SMK"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="kepsek",
            name="jenjang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TK", "TK"),
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("SMK", "SMK"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="master",
            name="jenjang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TK", "TK"),
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("SMK", "SMK"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="master_ekstrakulikuler",
            name="jenjang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TK", "TK"),
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("SMK", "SMK"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pembayaran",
            name="jenjang",
            field=models.CharField(
                choices=[
                    ("TK", "TK"),
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("SMK", "SMK"),
                ],
                max_length=255,
            ),
        ),
    ]
