# Generated by Django 5.1.1 on 2024-10-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0015_history_adendum_jumlah_siswa_tk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produk",
            name="list_sekolah",
            field=models.ManyToManyField(
                blank=True, related_name="produk", to="apps.master"
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="list_sekolah_ekstrakulikuler",
            field=models.ManyToManyField(
                blank=True, related_name="produk", to="apps.master_ekstrakulikuler"
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="list_sekolah",
            field=models.ManyToManyField(
                blank=True, related_name="sales", to="apps.master"
            ),
        ),
        migrations.AlterField(
            model_name="teknisi",
            name="list_sekolah",
            field=models.ManyToManyField(
                blank=True, related_name="teknisi", to="apps.master"
            ),
        ),
    ]
